exports.SUCCESSFUL = "SUCCESSFUL";
exports.FAILED = "FAILED";
exports.WRONG_PWD = "WRONG_PWD";
exports.WRONG_USERNAME = "WRONG_USERNAME";
exports.SESSION_EXPIRED = "SESSION_EXPIRED";
exports.IS_BANNED_ACCOUNT = "IS_BANNED_ACCOUNT";
exports.IS_UNACTIVATED_ACCOUNT = "IS_UNACTIVATED_ACCOUNT";